apiVersion: v1
kind: Pod
metadata:
  name: solar-prod-alert
spec:
  hostNetwork: true # allows to connect to the host-network and detect devices via mdns
  containers:
  - name: solar-prod-alert
    image: fgheysels/solarpoweralerter:015
    env:
    - name: HomeWizard__P1HostName
      value: p1meter-015AB0