apiVersion: apps/v1
kind: Deployment
metadata:
  name: solar-prod-alert
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solar-alerter
  template:
    metadata:
      labels:
        app: solar-alerter
    spec:
      hostNetwork: true # allows to connect to the host-network and detect devices via mdns
      containers:
      - name: solar-prod-alert
        image: fgheysels/solarpoweralerter:0.0.16
        env:
        - name: Logging__LogLevel__Default
          value: Information
        - name: HomeWizard__P1HostName
          value: p1meter-015AB0
        - name: QBus__IpAddress
          value: 192.168.1.14
        - name: QBus__Port
          value: "8444"
        - name: QBus__Username
          value: <provide-qbus-username>
        - name: QBus_Password
          value: <provide-qbus-password>
        - name: QBus__SolarIndicators
          value: SOLAR_INDICA
        - name: PowerUsageThresholds__NotEnoughProduction
          value: "200"
        - name: PowerUsageThresholds__OverProduction
          value: "-800"
        - name: PowerUsageThresholds__ExtremeOverProduction
          value: "-2500"