FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /app

COPY *.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish Fg.SolarProductionAlerter.csproj -c Release -o Fg.SolarProductionAlerter/out

FROM mcr.microsoft.com/dotnet/runtime:8.0-bookworm-slim-arm32v7

WORKDIR /app
COPY --from=build-env /app/Fg.SolarProductionAlerter/out ./
COPY qemu-arm-static /usr/bin/qemu-arm-static

ENTRYPOINT ["dotnet", "Fg.SolarProductionAlerter.dll"]